# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'

inputs:
  script:  # id of input
    description: 'The something you can input'
    required: false
    default: "deploy_webservice"
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/scripts/hello.sh
      shell: bash
      if: inputs.script == 'deploy_webservice'
    - run: bash ${{ github.action_path }}/scripts/goodbye.sh
      shell: bash
      if: inputs.script == 'deploy_function'
